### PR TITLE
ping-client\Server example

### PR DESCRIPTION
**Pull request by r-caamano**
Request to merge zping example to main sdk-golang examples.
zping emulates icmp echo response using ziti.

### CODE REVIEW

**Comment by plorenz** [comment]
Hi @r-caamano can you just run this through gofmt, then I can pull it in.

`go fmt ./examples/...`

**Comment by r-caamano** [comment]
Hi @plorenz thanks for letting me know.  fmt completed.

**Review by plorenz — APPROVED** [review]

**Comment by r-caamano** [comment]
@plorenz sorry I guess I mis-understood I needed to run fmt /example/... against all in example not just mine

**Comment by plorenz** [comment]
> @plorenz sorry I guess I mis-understood I needed to run fmt /example/... against all in example not just mine

Not a problem, the new code is clean. I can hit the old examples later

**Pull request merged**
